---
- hosts: localhost
  connection: local
  become: false
  tasks:
  - name: create key pair using provided key_material
    amazon.aws.ec2_key:
      name: ansible-diana
      key_material: 'Diana'
      